In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import os

In [2]:
def table_reader(filename):
    
    with open(filename, 'r') as strange_file:
        file = strange_file.read()
        
    strange_symbol = file[3]
    cleaned_file = file.replace(strange_symbol, '')

    soup = BeautifulSoup(cleaned_file, 'html.parser')
    
    table_container = [[i.text for i in row.find_all('td')] for row in soup.find_all('tr')]

    return pd.DataFrame(table_container[1:], columns=table_container[0])

In [3]:
#erro
#df1 = pd.read_excel('busca_sql_2012.xls', engine='xlrd')
#df1.info()

In [4]:
# Criando um dataframe para cada arquivo
dataframes = [table_reader(i) for i in os.listdir() if i.endswith('.xls')]

In [5]:
# Concatenando os dataframes a unindo os dados
df = pd.concat(dataframes)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 265718 entries, 0 to 8298
Data columns (total 8 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Número da Localização                          265718 non-null  object
 1   Número do Processo (Número do Protocolo)       265718 non-null  object
 2   Número do Protocolo (Número do Protocolo)      265718 non-null  object
 3   Assunto (Número do Protocolo)                  265718 non-null  object
 4   Situação da Solicitação (Número do Protocolo)  265718 non-null  object
 5   Ano (Número do Protocolo)                      265718 non-null  object
 6   Competência (Número do Protocolo)              265718 non-null  object
 7   Unidade Administrativa (Número do Protocolo)   265718 non-null  object
dtypes: object(8)
memory usage: 18.2+ MB

In [6]:
df.columns = ['sql', 'n_processo', 'n_protocolo', 'assunto', 'situacao', 'ano', 'competencia', 'unidade_administrativa']
df.head(20)

,sql,n_processo,n_protocolo,assunto,situacao,ano,competencia,unidade_administrativa
0,001.010.0026-1,2013-0.033.699-0,7016-12,Alvará de Aprovação de Edificação Nova,Indeferido,2.012,SMPR,Prefeitura Regional Sé
1,001.010.0026-1,2013-0.033.699-0,7016-12,Alvará de Aprovação de Edificação Nova,Indeferido,2.012,SMPR,Prefeitura Regional Sé
2,001.019.0160-7,2012-0.314.155-2,1985-12,Alvará de Aprovação de Edificação Nova,Indeferido,2.012,SMPR,Prefeitura Regional Sé
3,001.019.0160-7,2012-0.314.155-2,1985-12,Alvará de Aprovação de Edificação Nova,Indeferido,2.012,SMPR,Prefeitura Regional Sé
4,001.053.0362-3,2012-0.328.005-6,2678-12,Alvará de Aprovação de Reforma,Processo Físico,2.012,SMUL,PARHIS-G
5,001.053.0362-3,2012-0.328.005-6,2678-12,Alvará de Aprovação de Reforma,Processo Físico,2.012,SMUL,PARHIS-G
6,001.061.0030-0,2013-0.017.548-2,3952-12,Alvará de Aprovação de Reforma,Processo Físico,2.012,SMUL,SERVIN
7,001.061.0030-0,2013-0.017.548-2,3952-12,Alvará de Aprovação de Reforma,Processo Físico,2.012,SMUL,SERVIN
8,002.001.0061-0,2012-0.315.311-9,2064-12,Alvará de Aprovação de Reforma,Indeferido,2.012,SMPR,Prefeitura Regional Sé
9,002.001.0061-0,2012-0.315.311-9,2064-12,Alvará de Aprovação de Reforma,Indeferido,2.012,SMPR,Prefeitura Regional Sé
10,002.011.0005-3,2012-0.315.290-2,2489-12,Alvará de Aprovação de Reforma,Indeferido,2.012,SMUL,RESID
11,002.011.0005-3,2012-0.315.290-2,2489-12,Alvará de Aprovação de Reforma,Indeferido,2.012,SMUL,RESID
12,002.011.0006-1,2012-0.300.546-2,1537-12,Alvará de Aprovação de Reforma,Processo Físico,2.012,SMUL,COMIN
13,002.011.0006-1,2012-0.300.546-2,1537-12,Alvará de Aprovação de Reforma,Processo Físico,2.012,SMUL,COMIN
14,002.017.0033-6,2013-0.014.342-4,6928-12,Alvará de Desdobro de Lote,Em Análise,2.012,SMUL,PARHIS-3
15,002.017.0033-6,2013-0.014.342-4,6928-12,Alvará de Desdobro de Lote,Em Análise,2.012,SMUL,PARHIS-3
16,005.024.0014-5,2013-0.022.239-1,6486-12,Alvará de Aprovação de Edificação Nova,Processo Físico,2.012,SMUL,RESID
17,005.024.0014-5,2013-0.022.239-1,6486-12,Alvará de Aprovação de Edificação Nova,Processo Físico,2.012,SMUL,RESID
18,005.024.0488-4,2013-0.022.239-1,6486-12,Alvará de Aprovação de Edificação Nova,Processo Físico,2.012,SMUL,RESID
19,005.024.0488-4,2013-0.022.239-1,6486-12,Alvará de Aprovação de Edificação Nova,Processo Físico,2.012,SMUL,RESID

In [7]:
# Verificando os dados
df['ano'].value_counts()

2.014    32748
2.015    30479
2.019    27081
2.013    24858
2.018    24692
2.017    24590
2.020    23776
2.016    23559
2.021    21043
2.022    20639
2.023     8299
2.012     3954
Name: ano, dtype: int64

In [8]:
df.drop(columns=['ano'], inplace=True)
df.head()

,sql,n_processo,n_protocolo,assunto,situacao,competencia,unidade_administrativa
0,001.010.0026-1,2013-0.033.699-0,7016-12,Alvará de Aprovação de Edificação Nova,Indeferido,SMPR,Prefeitura Regional Sé
1,001.010.0026-1,2013-0.033.699-0,7016-12,Alvará de Aprovação de Edificação Nova,Indeferido,SMPR,Prefeitura Regional Sé
2,001.019.0160-7,2012-0.314.155-2,1985-12,Alvará de Aprovação de Edificação Nova,Indeferido,SMPR,Prefeitura Regional Sé
3,001.019.0160-7,2012-0.314.155-2,1985-12,Alvará de Aprovação de Edificação Nova,Indeferido,SMPR,Prefeitura Regional Sé
4,001.053.0362-3,2012-0.328.005-6,2678-12,Alvará de Aprovação de Reforma,Processo Físico,SMUL,PARHIS-G

In [16]:
with open('busca.txt', 'r') as busca_file:
    busca = [i[:-1] for i in busca_file.readlines()]

In [17]:
busca

['040.085.0005-7',
 '040.115.0020-8',
 '040.115.0018-6',
 '040.199.0140-6',
 '040.199.0023-1',
 '040.199.0022-0']

In [17]:
#cleaned_busca = [i[:2].zfill(3) + '.' + i[3:].zfill(3) for i in busca]

#with open('busca_sq_oficio2322-2023.txt', 'w') as file:
#    for i in cleaned_busca:
#        file.write(i + '\n')

In [30]:
#cleaned_busca_julio = ['"' + i:2].zfill(3) + '.' + i[3:].zfill(3) + '"' + ',' for i in busca]
cleaned_busca_julio = ['"' + i + '"' + ',' for i in busca]

with open('busca_ad2.txt', 'w') as file:
    for i in cleaned_busca_julio:
        file.write(i + ' ')

In [19]:
#df['sq'] = df['sql'].str[:7]
#df['sq']

In [20]:
busca_df = df.query("sql in @busca")

In [21]:
busca_df

Empty DataFrame
Columns: [sql, n_processo, n_protocolo, assunto, situacao, competencia, unidade_administrativa]
Index: []

In [16]:
busca_df.to_csv('busca_slce_23-06-23.csv', sep=';',encoding='latin1', index=False)

UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 19: ordinal not in range(256)

In [27]:
df = df.replace("\u2013", "-")

In [29]:
df.to_csv('test.csv', sep=';', index=False, encoding='utf-8')